name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  id-token: write  # REQUIRED for trusted publishing
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release  # Matches your PyPI trusted publisher config
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install uv
        run: pip install uv
      
      - name: Build package
        run: uv build
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
